[package]
name = "rag_pipeline"
version.workspace = true
edition.workspace = true

[dependencies]
mofa-foundation = { path = "../../crates/mofa-foundation", features = ["qdrant"] }
mofa-kernel = { path = "../../crates/mofa-kernel" }

tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures = "0.3"
async-trait = "0.1"
anyhow = "1.0"

[lints]
workspace = true
