[package]
name = "multi_agent_coordination"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
chrono = "0.4"
regex = "1"
serde.workspace = true
# Local dependencies
mofa-sdk = { path = "../../crates/mofa-sdk"}

# Workspace dependencies
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
