[package]
name = "message_graph_executor_runtime"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
serde_json.workspace = true

# Local dependencies
mofa-kernel = { path = "../../crates/mofa-kernel" }
