[package]
name = "react_agent"
version.workspace = true
edition.workspace = true

[dependencies]
mofa-sdk = { path = "../../crates/mofa-sdk"}

tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
async-trait.workspace = true
serde_json.workspace = true
[lints]
workspace = true
