[package]
name = "config"
version.workspace = true
edition.workspace = true

[dependencies]
# Local dependencies
mofa-sdk = { path = "../../crates/mofa-sdk" }

# Workspace dependencies
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
