[package]
name = "wasm_plugin"
version.workspace = true
edition.workspace = true

[dependencies]
# Local dependencies
mofa-sdk = { path = "../../crates/mofa-sdk" }

# Workspace dependencies
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasmtime = "40.0.0"
