[package]
name = "chat_stream"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
mofa-sdk = {path = "../../crates/mofa-sdk" }
tokio-stream = "0"
tracing.workspace = true
tracing-subscriber.workspace = true
[lints]
workspace = true
