[package]
name = "workflow_orchestration"
version.workspace = true
edition.workspace = true

[dependencies]
# Local dependencies
mofa-sdk = { path = "../../crates/mofa-sdk"}

# Workspace dependencies
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
