[package]
name = "structured_output"
version.workspace = true
edition.workspace = true

[dependencies]
mofa-foundation = { path = "../../crates/mofa-foundation" }
mofa-kernel = { path = "../../crates/mofa-kernel" }

tokio.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
