[package]
name = "rhai_hot_reload"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
mofa-sdk = { path = "../../crates/mofa-sdk" }
tokio = { version = "1.48.0", features = ["full"] }
tracing-subscriber = "0.3.22"
tracing = "0.1.44"
