[package]
name = "workflow_dsl"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
mofa-sdk = { path = "../../crates/mofa-sdk", features = ["openai"] }

anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
