[package]
name = "workflow_dsl"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
mofa-sdk = { path = "../../crates/mofa-sdk"}

tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("openai"))'] }
