[package]
name = "runtime_example"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true

# Local dependencies
mofa-sdk = { path = "../../crates/mofa-sdk" }

# Workspace dependencies
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
